const blogs = [
    {
        id: 1,
        title: "Mastering JavaScript for Beginners",
        content: "JavaScript is a versatile language used in web development...",
        categories: ["Programming", "JavaScript", "Web Development"],
        tags: ["JavaScript", "Coding Basics", "Frontend"],
        popularity: 8.7,
        isPopular: false,
        isRecent: true,
        date: "2024-10-01",
        image: "/cards/js.png",
        comments: ["Very helpful article!", "Great tips, thanks!"],
    },
    {
        id: 2,
        title: "Understanding React Hooks",
        content: "React hooks are a game-changer for building functional components...",
        categories: ["React", "Frontend Development"],
        tags: ["React", "Hooks", "JavaScript"],
        popularity: 9.3,
        isPopular: false,
        isRecent: true,
        date: "2024-12-15",
        image: "/cards/hook.png",
        comments: ["Hooks made my life easier!", "Detailed explanation."],
    },
    {
        id: 3,
        title: "The Future of AI in Healthcare",
        content: "Artificial Intelligence is revolutionizing the healthcare industry...",
        categories: ["AI", "Healthcare", "Technology"],
        tags: ["AI", "Healthcare", "Innovation"],
        popularity: 7.5,
        isPopular: true,
        isRecent: true,
        date: "2024-12-05",
        image: "/cards/ai.png",
        comments: ["This is amazing!", "AI is the future!"],
    },
    {
        id: 4,
        title: "Top 10 CSS Frameworks in 2024",
        content: "Choosing the right CSS framework can speed up development...",
        categories: ["CSS", "Web Design", "Frontend"],
        tags: ["CSS Frameworks", "Tailwind", "Bootstrap"],
        popularity: 9.0,
        isPopular: true,
        isRecent: false,
        date: "2024-09-15",
        image: "/cards/css.jpg",
        comments: ["Tailwind is the best!", "Bootstrap still rocks."],
    },
    {
        id: 5,
        title: "Why Python is the Go-To Language for Data Science",
        content: "Python has become a dominant force in data science due to...",
        categories: ["Python", "Data Science", "Machine Learning"],
        tags: ["Python", "Data Analysis", "ML"],
        popularity: 8.2,
        isPopular: false,
        isRecent: true,
        date: "2024-11-30",
        image: "/cards/py.jpg",
        comments: ["Informative read.", "Python forever!"],
    },
    {
        id: 6,
        title: "Getting Started with Next.js 14",
        content: "Next.js is the framework of choice for modern React developers...",
        categories: ["React", "Next.js", "Web Development"],
        tags: ["Next.js", "React", "Server-side Rendering"],
        popularity: 8.9,
        isPopular: true,
        isRecent: false,
        date: "2024-08-10",
        image: "/cards/nextjs.png",
        comments: ["I needed this guide!", "SSR is so useful."],
    },
    {
        id: 7,
        title: "UI/UX Trends to Watch in 2024",
        content: "The design world is constantly evolving. Here's what to expect...",
        categories: ["UI/UX", "Design"],
        tags: ["UI", "UX", "Trends"],
        popularity: 7.8,
        isPopular: false,
        isRecent: true,
        date: "2024-11-20",
        image: "/cards/ui.png",
        comments: ["Love the insights!", "Very futuristic."],
    },
    {
        id: 8,
        title: "Building REST APIs with Node.js",
        content: "Learn how to create RESTful APIs using Node.js and Express...",
        categories: ["Node.js", "Backend Development", "APIs"],
        tags: ["Node.js", "Express", "REST API"],
        popularity: 8.3,
        isPopular: false,
        isRecent: false,
        date: "2024-07-20",
        image: "/cards/aws.jpg",
        comments: ["Very clear examples.", "Great starter guide!"],
    },
    {
        id: 9,
        title: "The Rise of Web3 and Blockchain",
        content: "Blockchain technology is at the forefront of Web3 innovations...",
        categories: ["Web3", "Blockchain", "Cryptocurrency"],
        tags: ["Blockchain", "Web3", "Crypto"],
        popularity: 7.9,
        isPopular: false,
        isRecent: true,
        date: "2024-11-10",
        image: "/cards/web.jpg",
        comments: ["Very exciting topic!", "Crypto is the future!"],
    },
    {
        id: 10,
        title: "Deploying Your First App on AWS",
        content: "AWS offers a robust platform for deploying modern applications...",
        categories: ["AWS", "Cloud Computing", "DevOps"],
        tags: ["AWS", "Cloud", "DevOps"],
        popularity: 8.4,
        isPopular: true,
        isRecent: false,
        date: "2024-08-25",
        image: "/cards/aws.jpg",
        comments: ["Helpful tutorial.", "AWS made easy!"],
    },
    {
        id: 11,
        title: "The Complete Guide to Node.js and Express",
        content: "Node.js and Express are foundational for building fast and scalable web applications...",
        categories: ["Node.js", "Backend Development", "Web Development"],
        tags: ["Node.js", "Express", "API Development"],
        popularity: 8.5,
        isPopular: true,
        isRecent: true,
        date: "2024-11-25",
        image: "/cards/nodejs.png",
        comments: ["Great for beginners!", "Love the clear explanations."],
    },
    {
        id: 12,
        title: "How to Build Scalable Web Apps with Django",
        content: "Django is an excellent Python framework that simplifies building complex web applications...",
        categories: ["Django", "Python", "Web Development"],
        tags: ["Django", "Python", "Scalable Apps"],
        popularity: 8.8,
        isPopular: true,
        isRecent: false,
        date: "2024-10-22",
        image: "/cards/django.png",
        comments: ["Very informative guide.", "Django is my favorite framework!"],
    },
    {
        id: 13,
        title: "Mastering Vue.js for Dynamic Web Apps",
        content: "Vue.js is one of the most popular JavaScript frameworks, perfect for building interactive UIs...",
        categories: ["Vue.js", "Frontend Development", "JavaScript"],
        tags: ["Vue.js", "JavaScript", "Web Development"],
        popularity: 8.9,
        isPopular: false,
        isRecent: true,
        date: "2024-12-10",
        image: "/cards/vuejs.png",
        comments: ["Super helpful!", "Vue.js is amazing for smaller projects."],
    },
    {
        id: 14,
        title: "Understanding Web Security Best Practices",
        content: "In this article, we explore common security risks and best practices for securing web applications...",
        categories: ["Security", "Web Development", "Cybersecurity"],
        tags: ["Web Security", "Cybersecurity", "Best Practices"],
        popularity: 9.2,
        isPopular: true,
        isRecent: false,
        date: "2024-08-30",
        image: "/cards/security.png",
        comments: ["Very comprehensive!", "Security is so important."],
    },
    {
        id: 15,
        title: "Introduction to Machine Learning with Python",
        content: "Machine learning with Python is a powerful combination that allows you to solve complex problems with ease...",
        categories: ["Machine Learning", "Python", "AI"],
        tags: ["Machine Learning", "Python", "AI"],
        popularity: 9.1,
        isPopular: false,
        isRecent: true,
        date: "2024-12-05",
        image: "/cards/ml.png",
        comments: ["Python makes ML so much easier!", "Looking forward to more tutorials."],
    },
    {
        id: 16,
        title: "React vs Angular: Choosing the Right Framework",
        content: "React and Angular are two of the most popular front-end frameworks, but which one is right for your project?",
        categories: ["React", "Angular", "Frontend Development"],
        tags: ["React", "Angular", "Frameworks Comparison"],
        popularity: 8.3,
        isPopular: false,
        isRecent: false,
        date: "2024-07-15",
        image: "/cards/react-angular.png",
        comments: ["This helped me choose React!", "Great comparison of the two."],
    },
    {
        id: 17,
        title: "Exploring the Power of GraphQL",
        content: "GraphQL is a new query language for your API that allows you to fetch only the data you need...",
        categories: ["GraphQL", "API", "Backend Development"],
        tags: ["GraphQL", "API", "Backend"],
        popularity: 8.0,
        isPopular: true,
        isRecent: true,
        date: "2024-11-18",
        image: "/cards/graphql.png",
        comments: ["GraphQL is the future!", "Clear explanation of GraphQL."],
    },
    {
        id: 18,
        title: "Building Mobile Apps with Flutter",
        content: "Flutter allows you to build beautiful natively compiled applications for mobile from a single codebase...",
        categories: ["Flutter", "Mobile Development", "Cross-platform"],
        tags: ["Flutter", "Mobile Development", "Cross-platform"],
        popularity: 8.7,
        isPopular: true,
        isRecent: false,
        date: "2024-09-25",
        image: "/cards/flutter.png",
        comments: ["Best framework for mobile!", "Loved the hands-on guide."],
    },
    {
        id: 19,
        title: "Creating Stunning User Interfaces with Tailwind CSS",
        content: "Tailwind CSS is a utility-first CSS framework that makes building custom designs faster and easier...",
        categories: ["CSS", "Web Design", "Frontend Development"],
        tags: ["Tailwind CSS", "UI", "Frontend"],
        popularity: 8.4,
        isPopular: false,
        isRecent: true,
        date: "2024-11-02",
        image: "/cards/tailwind.webp",
        comments: ["Tailwind is the best for rapid prototyping.", "Great for responsive design."],
    },
    {
        id: 20,
        title: "The Future of Blockchain and Decentralized Applications",
        content: "Blockchain technology is transforming the way we think about data security, privacy, and decentralized applications...",
        categories: ["Blockchain", "Web3", "Cryptocurrency"],
        tags: ["Blockchain", "Decentralized Apps", "Web3"],
        popularity: 8.6,
        isPopular: false,
        isRecent: false,
        date: "2024-06-10",
        image: "/cards/blockchain.png",
        comments: ["Blockchain is here to stay.", "Very exciting future for DApps!"],
    },
];

export default blogs;
